spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nasdb.cksuboahrnk5.ap-northeast-1.rds.amazonaws.com:3306/nas_db?serverTimezone=Asia/Seoul
    username: root
    password: gcs12345

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50